### ISSUE TITLE
Suporte php 7.4

### ISSUE THREAD

**Issue by caiolima86** [gpupo/mercadolivre-sdk#11]
Quero primeiramente agradecer pela biblioteca...
Infelizmente não estou conseguindo instalar pelo composer, diz precisar ter a versão 8 do php e eu utilizo a 7.4..
Atualizei meu composer para a versão do php 8.0, porém não consigo instalar, pois outras libs do meu projeto não suportam =/
Por favor, deixe a lib suportando a partir da versão 7.4 do php

Obrigado.

**Comment by caiolima86** [comment]
Mesmo atualizando as libs do meu projeto e tentando instalar essa, ainda recebo o erro:
 - gpupo/common[1.6.0, ..., 1.7.7] require php ^5.6 || ^7.0 -> your php version (8.1.0beta3) does not satisfy that requirement.

**Comment by caiolima86** [comment]
Consegui resolver deixando meu composer com php 7.4, o problema estava na lib monolog/monolog

**Comment by gpupo** [comment]
@caiolima86 você pode usar versões anteriores (vá em `Releases`)
